#!/bin/sh -e

cd /etc/netns/novpn

flag_a=0
flag_d=0

while getopts "a:d:f" flag
do
    case $flag in
        a)
            flag_a=1
            ;;
        d)
            flag_d=1
            ;;
    esac
done

make_resolv_conf() {
    cat resolv.conf.d/* > /etc/resolv.conf
}

if [ $flag_a -eq 1 ]
then
    cat > resolv.conf.d/head
    make_resolv_conf
elif [ $flag_d -eq 1 ]
then
    rm resolv.conf.d/head
    make_resolv_conf
else
    exit 1
fi
